### ISSUE TITLE
支出京豆有误，大佬得空看看呀

### ISSUE THREAD

**Issue by zYy-218** [dompling/Scriptable#1]
大佬，昨日支出和昨日收入数据一样。
还有左上角图标位置有点问题，该怎么调，谢谢。
![image](https://user-images.githubusercontent.com/13390086/97939128-354a8500-1dbe-11eb-9ee4-f90f972a3597.jpeg)

**Comment by dompling** [comment]
> 大佬，昨日支出和昨日收入数据一样。
> 还有左上角图标位置有点问题，该怎么调，谢谢。
> ![image](https://user-images.githubusercontent.com/13390086/97939128-354a8500-1dbe-11eb-9ee4-f90f972a3597.jpeg)
好的，看到了。已经修复了。重新更新一下应该可以了。
