### ISSUE TITLE
scriptable无法访问

### ISSUE THREAD

**Issue by sailcom** [dompling/Scriptable#23]
请问大神scriptable目前是否还维护？
我是新手，想了解安装方式，但相关的群以及软件都无法安装打开。
请问有无其他途径可以看到相关的教程？感谢大神

**Comment by dompling** [comment]
> 请问大神scriptable目前是否还维护？ 我是新手，想了解安装方式，但相关的群以及软件都无法安装打开。 请问有无其他途径可以看到相关的教程？感谢大神

群无法打开吗？https://t.me/+ViT7uEUrIUV0B_iy

**Comment by sailcom** [comment]
README.md文档中的链接该更新了 😄 
已加，谢谢
